### PR TITLE
Proofreading edits: comments/docstrings/text strings

### PR DESCRIPTION
**Pull request by kaakmal**
- Made docstring formatting consistent (sentence case, no periods)
- Fixed some mild grammar issues
-"VZOR" and "spess" weren't variable names that made sense to me as an English speaker (not words or clear abbreviations), but I left them as-is since variable names can be anything. It might be worth changing them to something easier to understand since this is example code.
-  I didn't realize that there was a template until I opened that file, so for all files after the template, I ignored the template code, since that can be copy-pasted.

### CODE REVIEW

**Review by onekk — APPROVED** [review]

**Review by onekk — APPROVED** [review]

**Review by onekk — APPROVED** [review]

**Review by onekk — APPROVED** [review]
Ok, many thanks

**Review by onekk — APPROVED** [review]

**Comment by onekk** [comment]
Hello, I see your comment about variable names, as I'm Italian, some variable have meaning in my language.

Some of the original code was written for the Italian version, so some remnants of Italian are present.

For "historical reason" I will left some variables here, maybe we could improve "documentation" inserting some comments in code to tell what  element the variable is "adjusting".

Many thanks, again, I'm not very skilled in Github operations, so I hope everything is correct in the merge.

Side note: I will improve some more in a new push docstring format, as I've set my editor to make PEP8 checks.

Regards

Carlo D.

**Comment by kaakmal** [comment]
I checked and it merged fine. 

A comment line clarifying what the variable is would be a good solution if changing the name would cause issues elsewhere. 

If you're willing to add the LaTeX code to the repository, I can do this for the PDF instructions too.

**Comment by onekk** [comment]
My Latex generation is almost complicated, as it uses many packages, it is not very "human readable" as many phrases use the glossary entry instead if the real "word". 

We could agree in some intermediate things, Let's me see if I could produce something like HTML or markdown from sources, so it will be more easy to make corrections for proof reader.

My work remains complicated, but this is not a problem for me.

Let me study the thing for a couple of days.

TIA and Regards.

Carlo D.

**Comment by onekk** [comment]
Many Thanks again, could you please to see the new files.

- I have used your suggestions to modify all the things
- In the meantime, I have run some check and made the code hopefully more pep8 compliant using flake8, you will note some #noqa comments. They are to instruct flake8 to not parse line, as errors in these lines are "intentional", same for period at the end of docstrings, flake8 enforce a Capital letter as first character and a period as last character.

Hoping to have integrated all your modifications, as I've done some mess in importing on my local tree modifications merged.

:-( I've to study some more GitHub 

Regards

Carlo D.

**Comment by kaakmal** [comment]
Ah, so you've got sentences like "The \word{thing1} is used to \word{thing2}."? I'm pretty comfortable with LaTeX (I've done internal references, bibliographies, math environments, TikZ, a few custom commands...), so that sort of thing probably wouldn't be an issue, but it's fine if you'd be more comfortable sharing HTML, markdown, etc. 

I saw a couple of things that flake8 will complain about (typing #noqua instead of #noqa, forgetting a period at the end of a docstring) but nothing I would personally see as a problem. Your revisions look good.

When I tried to use the "fetch upstream" tool, it was convinced there were unresolvable conflicts, but I dealt with that by just deleting my fork and re-forking (which is maybe what I should have done in the first place).

**Comment by onekk** [comment]
I have some mess in the repo  where I develop the guide, it is a sub repository of a more big thing, I have to move it in something more accessible.

But as I don't want it to be "public" I have to find a way to grant some access to other users.

Did you have a Atlassians BitBucket account?

Regards

Carlo D.

**Comment by kaakmal** [comment]
Not currently, but I can get a free one if that'll be good enough.

**Comment by onekk** [comment]
Not necessary anymore, I have created a private GitHub page for the translations.

And I've send you an invite to permit editing and visibility of the page.

It is my first try so let me know if anything is wrong.

Regards

Carlo D.

**Comment by kaakmal** [comment]
Hmm. The invitation link I got sent me to a 404 page not found. Did you
accidentally delete either the repository or the invitation?

**Comment by onekk** [comment]
@kaakmal  I've sent you a new invitation.

Maybe it is because I've change Repo Name.

Resent.

**Pull request merged**
